const Constants = {
    AUTH_SUCCESS: 'AUTH_SUCCESS',
    AUTH_FAIL: 'AUTH_FAIL',
    AUTH_ERROR: 'AUTH_ERROR',

    TABLE_DATA_SUCCESS: 'TABLE_DATA_SUCCESS',
    TABLE_DATA_ERROR: 'TABLE_DATA_ERROR'
}

export default Constants;